version: '3.9'

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: world_cup_pool
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build:
      context: ./back
    command: ./entrypoint.sh
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/world_cup_pool
      DJANGO_DEBUG: '1'
      DJANGO_ALLOWED_HOSTS: 'localhost,127.0.0.1'
      DJANGO_SECRET_KEY: 'django-insecure-local'
    ports:
      - '8000:8000'
    depends_on:
      - postgres
    volumes:
      - ./back:/app

  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  postgres-data:
