# Generated by Codex on 2026-06-01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid


def pool_code_default():
    return shortuuid.ShortUUID().random(length=8)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=5)),
                ("image", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("avatar", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pool",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("cod", models.CharField(default=pool_code_default, max_length=100)),
                ("created_at", models.DateTimeField()),
                ("correct_score", models.CharField(max_length=10)),
                ("result_score", models.CharField(max_length=10)),
                ("avatar", models.CharField(blank=True, max_length=100, null=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.participant")),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_game", models.DateTimeField()),
                ("date_closing_game", models.DateTimeField()),
                ("score_first_team", models.CharField(blank=True, max_length=20, null=True)),
                ("score_second_team", models.CharField(blank=True, max_length=20, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("stadium", models.CharField(blank=True, max_length=100, null=True)),
                ("round", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "first_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="first_team", to="api.country"
                    ),
                ),
                (
                    "second_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="second_team", to="api.country"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParticipantPool",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("participant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.participant")),
                ("pool", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.pool")),
            ],
        ),
        migrations.CreateModel(
            name="Guess",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guess_first_team", models.CharField(max_length=10)),
                ("guess_second_team", models.CharField(max_length=10)),
                ("game", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.game")),
                ("participant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.participantpool")),
            ],
            options={
                "unique_together": {("game", "participant")},
            },
        ),
    ]
