# Generated by Django 3.2.12 on 2026-06-10 11:49

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_timezone_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='cod',
            field=models.CharField(default=api.models.pool_code_default, max_length=100),
        ),
    ]
